version: 2
jobs:
  e2e_cypress:
    docker:
    - image: cypress/base:8
      environment:
        TERM: xterm
    working_directory: ~/app
    steps:
    - checkout
    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - v{{ .Environment.versionCache }}-deps-{{ .Branch }}-
          - v{{ .Environment.versionCache }}-deps-
    - run: yarn install --frozen-lockfile
    - save_cache:
        name: Save Yarn Package Cache
        key: v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache
    - run:
        name: Running E2E tests
        command: yarn test:e2e:ci
    - store_test_results:
        path: test-results
    - store_artifacts:
        path: cypress/videos
    - store_artifacts:
        path: cypress/screenshots

workflows:
  version: 2
  testing:
    jobs:
      - e2e_cypress