describe('Blog', () => {
  beforeEach(() => {
    cy.visit('/blog')
  })
  it('Cover links to Blogpost', () => {
    cy.getByTitle('Quicktipp: Netlify + Discord')
      .click()
      .getByText('Quicktipp: Netlify + Discord')
      .should('exist')
  })
  it('Title links to Blogpost', () => {
    cy.getByText('Quicktipp: Netlify + Discord')
      .click()
      .getByText('Quicktipp: Netlify + Discord')
      .should('exist')
  })
  it('Category links to overview of that Category', () => {
    cy.getByText('Quicktipp')
      .click()
      .getByTestId('header-title')
      .should('contain', 'Quicktipp')
      .getByText('Quicktipp: Netlify + Discord')
      .should('exist')
  })
  it('Tag in the Blogpost links to overview of that Tag', () => {
    cy.getByText('Quicktipp: Netlify + Discord')
      .click()
      .getByTestId('tag-Discord')
      .click()
      .getByTestId('header-title')
      .should('contain', 'Discord')
      .getByText('Quicktipp: Netlify + Discord')
      .should('exist')
  })
})
