describe('Home', () => {
  beforeEach(() => {
    cy.visit('/')
  })
  it('Featured Projects load', () => {
    cy.getByTestId('featured-project-0')
      .click()
      .getByText('Kunde')
      .should('exist')
    cy.visit('/')
      .getByTestId('featured-project-1')
      .click()
      .getByText('Kunde')
      .should('exist')
    cy.visit('/')
      .getByTestId('featured-project-2')
      .click()
      .getByText('Kunde')
      .should('exist')
  })
  it('Featured Posts load', () => {
    cy.getByTestId('featured-post-0')
      .click()
      .getByText('Weitere Blogeinträge')
      .should('exist')
    cy.visit('/')
      .getByTestId('featured-post-1')
      .click()
      .getByText('Weitere Blogeinträge')
      .should('exist')
  })
  it('Button to projects works', () => {
    cy.get('a[type="primary"]')
      .should('contain', 'Projekte')
      .click()
      .assertRoute('/projects')
  })
  it('Button to blog works', () => {
    cy.get('a[type="secondary"]')
      .should('contain', 'Blog')
      .click()
      .assertRoute('/blog')
  })
})
