describe('Home German', () => {
  beforeEach(() => {
    cy.visit('/').waitForRouteChange()
  })
  it('Index button (Projects) work', () => {
    cy.get('a[type="primary"]')
      .should('contain', 'Projekte')
      .click()
      .waitForRouteChange()
      .assertRoute('/projects')
  })
  it('Index button (Blog) work', () => {
    cy.get('a[type="secondary"]')
      .should('contain', 'Blog')
      .click()
      .waitForRouteChange()
      .assertRoute('/blog')
  })
  it('Featured Projects load', () => {
    cy.getByTestId('featured-project-0')
      .click()
      .waitForRouteChange()
      .getByText('Kunde')
    cy.visit('/')
      .getByTestId('featured-project-1')
      .click()
      .waitForRouteChange()
      .getByText('Kunde')
    cy.visit('/')
      .getByTestId('featured-project-2')
      .click()
      .waitForRouteChange()
      .getByText('Kunde')
  })
  it('Featured Posts load', () => {
    cy.getByTestId('featured-post-0')
      .click()
      .waitForRouteChange()
      .getByText('Weitere Beiträge')
    cy.visit('/')
      .getByTestId('featured-post-1')
      .click()
      .waitForRouteChange()
      .getByText('Weitere Beiträge')
  })
})
