describe('Navigation German', () => {
  beforeEach(() => {
    cy.visit('/').waitForRouteChange()
  })
  it('in the header works', () => {
    cy.get('nav').within(() => {
      cy.getByText('Projekte')
        .click({ force: true })
        .waitForRouteChange()
        .assertRoute('/projects')
    })
    cy.getByText('Blog')
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/blog')
      .getByText('Kontakt')
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/contact')
      .getByLabelText(/LekoArts, Back to homepage/)
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/')
  })
  it('to external sites in the footer works', () => {
    cy.getByText('Behance')
      .should('have.prop', 'href', 'https://www.behance.net/lekoarts')
      .getByText('Dribbble')
      .should('have.prop', 'href', 'https://dribbble.com/LekoArts')
      .getByText('GitHub')
      .should('have.prop', 'href', 'https://github.com/LekoArts')
      .getByText('Instagram')
      .should('have.prop', 'href', 'https://www.instagram.com/lekoarts.de')
      .getByText('Patreon')
      .should('have.prop', 'href', 'https://www.patreon.com/lekoarts')
  })
  it('to internal sites in the footer works', () => {
    cy.getByText('Datenschutzerklärung')
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/privacy')
      .getByText('Tutorials')
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/categories/tutorial')
      .getByText('Impressum')
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/imprint')
      .getByText('Freebies')
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/categories/freebie')
  })
})
