describe('Navigation German', () => {
  beforeEach(() => {
    cy.visit('/')
  })
  it('in the header works', () => {
    cy.get('nav').within(() => {
      cy.findByText('Projekte')
        .click({ force: true })
        .waitForRouteChange()
        .assertRoute('/projects')
    })
    cy.findByText('Blog')
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/blog')
      .findByText('Kontakt')
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/contact')
      .findByLabelText(/LekoArts, Back to homepage/)
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/')
  })
  it('to external sites in the footer works', () => {
    cy.findByText('Behance')
      .should('have.prop', 'href', 'https://www.behance.net/lekoarts')
      .findByText('Dribbble')
      .should('have.prop', 'href', 'https://dribbble.com/LekoArts')
      .findByText('GitHub')
      .should('have.prop', 'href', 'https://github.com/LekoArts')
      .findByText('Instagram')
      .should('have.prop', 'href', 'https://www.instagram.com/lekoarts.de')
      .findByText('Patreon')
      .should('have.prop', 'href', 'https://www.patreon.com/lekoarts')
  })
  it('to internal sites in the footer works', () => {
    cy.findByText('Datenschutzerklärung')
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/privacy')
      .findByText('Tutorials')
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/categories/tutorial')
      .findByText('Impressum')
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/imprint')
      .findByText('Freebies')
      .click({ force: true })
      .waitForRouteChange()
      .assertRoute('/categories/freebie')
  })
})
