describe('Navigation German', () => {
  beforeEach(() => {
    cy.visit('/')
  })
  it('in the header works', () => {
    cy.getByText('Projekte')
      .click()
      .assertRoute('/projects')
      .getByText('Blog')
      .click()
      .assertRoute('/blog')
      .getByText('Kontakt')
      .click()
      .assertRoute('/contact')
      .getByText('LekoArts')
      .click()
  })
  it('to external sites in the footer works', () => {
    cy.getByText('Behance')
      .should('have.prop', 'href', 'https://www.behance.net/lekoarts')
      .getByText('Dribbble')
      .should('have.prop', 'href', 'https://dribbble.com/LekoArts')
      .getByText('GitHub')
      .should('have.prop', 'href', 'https://github.com/LekoArts')
      .getByText('Instagram')
      .should('have.prop', 'href', 'https://www.instagram.com/lekoarts.de')
      .getByText('Patreon')
      .should('have.prop', 'href', 'https://www.patreon.com/lekoarts')
  })
  it('to internal sites in the footer works', () => {
    cy.getByText('Datenschutzerklärung')
      .click()
      .assertRoute('/privacy')
      .getByText('Tutorials')
      .click()
      .assertRoute('/categories/tutorial')
      .getByText('Impressum')
      .click()
      .assertRoute('/imprint')
      .getByText('Freebies')
      .click()
      .assertRoute('/categories/freebie')
  })
})
