describe('Project & Blogpost', () => {
  it('Suggestions work', () => {
    cy.visit('/projekte/krotus-computer-produktion-einer-eigenen-tastatur')
      .getByText('Kunde')
      .should('exist')
      .getByTestId('suggestion-left')
      .click()
      .getByText('Kunde')
      .should('exist')
      .getByTestId('suggestion-right')
      .click()
      .getByText('Kunde')
      .should('exist')
  })
  it('Project footer links to contact', () => {
    cy.visit('/projekte/krotus-computer-produktion-einer-eigenen-tastatur')
      .getByText('Projekt starten')
      .click()
      .assertRoute('/kontakt')
  })
  it('Blogpost footer links to patreon', () => {
    cy.visit('/blog/quicktipp-netlify-discord')
      .getByText('Patreon')
      .should('have.prop', 'href', 'https://www.patreon.com/lekoarts')
  })
})
